### ISSUE TITLE
Xcode project for MacOS refers to file that does not exist.

### ISSUE THREAD

**Issue by PaulHaeberli** [thomasokken/free42#2] opened 2019-09-22 18:46 UTC
Nice project!

When trying to build for MacOS with Xcode I get this error:

error: Build input file cannot be found: '/Users/XXXXX/Downloads/free42-master/mac/readtest_lines.cc'

I fixed it by simply doing

touch free42-master/mac/readtest_lines.cc

**Comment by thomasokken** [comment] 2019-09-22 20:34
That file is created when the Intel library is built; see the Run Script item under Build Phases. You should be able to build from a clean checkout without any preparations. Although I'll admit I don't do clean checkouts all that often... If this is something you can reproduce, what are the steps, and which version of Xcode are you using?

**Comment by PaulHaeberli** [comment] 2019-09-22 21:16
It is repeatable.  

I am using Xcode Version 11.0 beta 2 (11M337n) on MacOS Catalina 10.15 Beta (19A536g)

1. Download the repo, unzip it.

2. cd free42-master/mac

3. Open Free42.xcodeproj

4. Go to "Signing & Capabilities", set Team and Bundle Identifier.

5. Select "Product > Clean Build Folder"

6. Select "Run"

I am downloading latest Xcode and will try also.

**Comment by PaulHaeberli** [comment] 2019-09-22 22:41
Same problem with iPhone project.

**Comment by thomasokken** [comment] 2019-09-22 23:04
I tried both builds from a clean checkout (git clone --local) and they ran without errors. Xcode 11.0. The Xcode version shouldn't matter, I guess, now that I think about it... I haven't made changes to the structure of the project in quite some time. Whatever is different between my setup and yours must be outside the source tree. When you create that dummy file, does everything else work okay, including the Intel library?

**Comment by thomasokken** [comment] 2019-09-22 23:06
N.B. Not sure if this matters, but I'm running MacOS 10.14.6.

**Comment by PaulHaeberli** [comment] 2019-09-22 23:35
One additional piece of info.  After the error on the first compile, If I just try to 
run again, the compile works without errors the secoend time.  It may be some 
Xcode bug.

You may be able to duplicate this behaviour by creating a new user on your mac and 
downloading the project and going though the steps.

No big deal - guess I should have been more persistent with Xcode.

**Comment by thomasokken** [comment] 2019-09-22 23:36
Ah, got it. The difference is that I didn't do Clean Build Folder. When I do that, I get the same error you do. Which begs the question: what happens when you clone the repo, and then run a build without doing Clean Build Folder first?

**Comment by thomasokken** [comment] 2019-09-22 23:37
Not sure how to fix this otherwise. If I put in a dummy file, git is going to want to commit the new version that gets generated when the Intel library is built, and I don't want to put a generated file under source control...

**Comment by thomasokken** [comment] 2019-09-23 00:05
BTW, did Free42 get mentioned on a blog or featured somewhere? The number of stars had crept up to 5 in the two weeks or so since I put this code in GutHub, and today it shot up to 19. Something's going on! 😱

**Comment by PaulHaeberli** [comment] 2019-09-23 00:22
Yes - I think it was just on Hacker News!

https://news.ycombinator.com/item?id=21042573

I guess we have to remember how flaky Xcode is....

    https://www.textfromxcode.com/

**Comment by thomasokken** [comment] 2019-09-23 00:47
Ah, cool. Thanks!

Xcode is a peculiar animal alright. Although it is better than it used to be. It's been years since the last time I screamed in rage because I just couldn't get app signing to work. 😄

OK, I'll close this issue, since I can't think of anything to do to improve the build behavior. I guess generated files that are also project members are just not handled well.

**Closed by thomasokken** 2019-09-23 00:47 UTC

**Comment by PaulHaeberli** [comment] 2019-09-23 01:06
Sounds fine. Nice project!

**Comment by thomasokken** [comment] 2019-09-23 01:12
Thanks! 😊
